Repository HanghaePlus-Team-7/Delivery-0111, pull requests merged in 2023-07, with the labels that each got.

#29 PR: `README.md` 작성
  README.md
Labels: documentation

#30 PR: 각 테스트마다 새로운 데이터 생성하도록 변경
  test/orders/orders-store.e2e-spec.ts
  test/truncate-table.ts
Labels: enhancement

#33 PR: 바뀐 파일명으로 수정
  src/common/set-nest-app.ts
  src/main.ts
  test/orders/orders-store.e2e-spec.ts
Labels: bug

#34 PR: user 폴더 구조 변경, create-user 분리
  src/modules/orders/entities/orders.entity.ts
  src/modules/user/dto/request/create-user.dto.ts
  src/modules/user/entities/user.entity.ts
  src/modules/user/service/create-user/create-user.interface.ts
  src/modules/user/service/create-user/create-user.service.spec.ts
  src/modules/user/service/create-user/create-user.service.ts
  src/modules/user/service/user.interface.ts
  src/modules/user/service/user.service.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.entity.ts
  src/modules/user/user.module.ts
  src/modules/user/user.repository.ts
Labels: enhancement

#36 PR: CICD 적용
  .aws/task-definition.json
  .dockerignore
  .github/workflows/push-to-ecr.yml
  .github/workflows/test-before-open-pr.yml
  Dockerfile
  docker-compose.production.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/middleware/logger.middleware.ts
  src/middleware/logger.module.ts
  src/middleware/winston-logger.ts
  src/modules/orders/orders.controller.ts
  tsconfig.json
Labels: enhancement

#39 PR: 주문확정 시간 생성 추가
  prisma/migrations/20230719082217_add_order_status_time/migration.sql
  prisma/migrations/20230719082947_drop_not_null_of_order_status_time/migration.sql
  prisma/schema.prisma
  src/modules/auth/service/confirm-order.service.spec.ts
  src/modules/orders/controller/dto/confirm-orders.request.ts
  src/modules/orders/controller/orders.controller.spec.ts
  src/modules/orders/controller/orders.controller.ts
  src/modules/orders/dto/command/confirm-orders.command.ts
  src/modules/orders/dto/request/confirm-orders.dto.ts
  src/modules/orders/entities/orders.entity.ts
  src/modules/orders/entities/orders.interface.ts
  src/modules/orders/entities/orders.type.ts
  src/modules/orders/repository/orders.prisma-repository.spec.ts
  src/modules/orders/repository/orders.prisma-repository.ts
  src/modules/orders/repository/orders.repository.ts
  src/modules/orders/service/dto/update-order-status.command.ts
  src/modules/orders/service/orders.service-impl.spec.ts
  src/modules/orders/service/orders.service-impl.ts
  src/modules/orders/service/orders.service.ts
  src/modules/orders/usecase/confirm-order/confirm-order-impl.spec.ts
  src/modules/orders/usecase/confirm-order/confirm-order-impl.ts
  src/modules/orders/usecase/confirm-order/confirm-order.ts
  test/orders/orders-store.e2e-spec.ts
Labels: enhancement

#40 PR: 알림보내기 service -> usecase로 변경
  src/modules/notification/notification.module.ts
  src/modules/notification/notification.service-impl.spec.ts
  src/modules/notification/notification.service-impl.ts
  src/modules/notification/notification.service.ts
  src/modules/notification/usecase/interfaces/notification-param.ts
  src/modules/notification/usecase/send-notification-impl.spec.ts
  src/modules/notification/usecase/send-notification-impl.ts
  src/modules/notification/usecase/send-notification.ts
  src/modules/orders/orders.module.ts
  src/modules/orders/service/orders.service-impl.spec.ts
  src/modules/orders/service/orders.service-impl.ts
Labels: enhancement

#41 PR: 메뉴 추가 api e2e 테스트 추가
  package-lock.json
  package.json
  src/middleware/multer/multer-config.service.ts
  src/modules/products/controller/dto/add-product.request.ts
  src/modules/products/controller/products.controller.spec.ts
  src/modules/products/controller/products.controller.ts
  src/modules/products/products.entity.ts
  src/modules/products/products.module.ts
  src/modules/products/service/dto/add-product.command.ts
  src/modules/products/service/product.service-impl.spec.ts
  src/modules/products/service/product.service-impl.ts
  src/modules/products/service/product.service.ts
  src/utils/is-exist-file.ts
  test/data/menu-test-img/test-menu-photo.png
  test/products/products.e2e-spec.ts
Labels: enhancement

#45 PR: 알림 이벤트 구독 방식으로 변경
  package-lock.json
  package.json
  src/app.module.ts
  src/libs/decorator/on-safe-event.decorator.ts
  src/modules/notification/notification.event.ts
  src/modules/notification/notification.module.ts
  src/modules/notification/service/interfaces/notification-param.ts
  src/modules/notification/service/notification.service.spec.ts
  src/modules/notification/service/notification.service.ts
  src/modules/notification/usecase/send-notification-impl.spec.ts
  src/modules/notification/usecase/send-notification-impl.ts
  src/modules/notification/usecase/send-notification.ts
  src/modules/order/order.module.ts
  src/modules/order/service/order.service-impl.spec.ts
  src/modules/order/service/order.service-impl.ts
  tsconfig.json
Labels: enhancement

#46 PR: 상품 추가 생성
  prisma/migrations/20230723121735_add_description_image_to_production/migration.sql
  prisma/schema.prisma
  src/libs/utils/is-uuid.ts
  src/modules/order/repository/order.prisma-repository.spec.ts
  src/modules/product/controller/dto/add-product.request.spec.ts
  src/modules/product/controller/dto/add-product.request.ts
  src/modules/product/entity/product.entity.spec.ts
  src/modules/product/product.module.ts
  src/modules/product/repository/interface/add-product-param.ts
  src/modules/product/repository/product.prisma-repository.spec.ts
  src/modules/product/repository/product.prisma-repository.ts
  src/modules/product/repository/product.repository.ts
  src/modules/product/service/dto/add-product.command.spec.ts
  src/modules/product/service/dto/add-product.command.ts
  src/modules/product/service/product.service.spec.ts
  src/modules/product/service/product.service.ts
  src/modules/product/usecase/add-product/add-product.spec.ts
  src/modules/product/usecase/add-product/add-product.ts
  test/orders/orders-store.e2e-spec.ts
Labels: enhancement

#47 PR: change method name
  src/modules/notification/service/notification.service.ts
Labels: enhancement

#48 PR: `getAllProducts` 기능 및 테스트 코드 추가
  src/modules/product/controller/product.controller.ts
  src/modules/product/entity/product.entity.ts
  src/modules/product/product.module.ts
  src/modules/product/repository/product.prisma-repository.spec.ts
  src/modules/product/repository/product.prisma-repository.ts
  src/modules/product/repository/product.repository.ts
  src/modules/product/service/product.service.spec.ts
  src/modules/product/service/product.service.ts
  src/modules/product/usecase/get-all-products/get-all-products.ts
  test/products/products.e2e-spec.ts
Labels: enhancement

#49 PR: `photoPath` -> `image` 로 이름 변경
  src/libs/decorator/on-safe-event.decorator.ts
  src/modules/order/controller/dto/confirm-order.request.ts
  src/modules/order/controller/order.controller.spec.ts
  src/modules/order/controller/order.controller.ts
  src/modules/product/controller/dto/add-product.request.spec.ts
  src/modules/product/controller/dto/add-product.request.ts
  src/modules/product/entity/product.entity.spec.ts
  src/modules/product/entity/product.entity.ts
  src/modules/product/repository/product.prisma-repository.spec.ts
  src/modules/product/repository/product.prisma-repository.ts
  src/modules/product/service/dto/add-product.command.spec.ts
  src/modules/product/service/dto/add-product.command.ts
  src/modules/product/service/product.service.spec.ts
  src/modules/product/usecase/add-product/add-product.spec.ts
  src/modules/product/usecase/add-product/add-product.ts
  test/products/products.e2e-spec.ts
Labels: enhancement

#50 PR: service layer 삭제
  src/modules/product/controller/dto/add-product.request.spec.ts
  src/modules/product/controller/dto/add-product.request.ts
  src/modules/product/controller/product.controller.ts
  src/modules/product/entity/product.entity.spec.ts
  src/modules/product/product.module.ts
  src/modules/product/repository/interface/add-product-param.ts
  src/modules/product/repository/product.prisma-repository.spec.ts
  src/modules/product/repository/product.prisma-repository.ts
  src/modules/product/repository/product.repository.ts
  src/modules/product/service/product.service.spec.ts
  src/modules/product/service/product.service.ts
  src/modules/product/usecase/add-product.use-case.spec.ts
  src/modules/product/usecase/add-product.use-case.ts
  src/modules/product/usecase/add-product/add-product.ts
  src/modules/product/usecase/dto/add-product.command.spec.ts
  src/modules/product/usecase/dto/add-product.command.ts
  src/modules/product/usecase/get-all-products.use-case.spec.ts
  src/modules/product/usecase/get-all-products.use-case.ts
  test/data/product-test-img/test-product-photo.png
  test/products/products.e2e-spec.ts
Labels: enhancement
